-- Name: Ishaan Sathaye
-- Cal Poly Email: isathaye@calpoly.edu

INSERT INTO Customers
	VALUES (1, 'LOGAN', 'JULIET');
INSERT INTO Customers
	VALUES (2, 'ARZT', 'TERRELL');
INSERT INTO Customers
	VALUES (3, 'ESPOSITA', 'TRAVIS');
INSERT INTO Customers
	VALUES (4, 'ENGLEY', 'SIXTA');
INSERT INTO Customers
	VALUES (5, 'DUNLOW', 'OSVALDO');
INSERT INTO Customers
	VALUES (6, 'SLINGLAND', 'JOSETTE');
INSERT INTO Customers
	VALUES (7, 'TOUSSAND', 'SHARRON');
INSERT INTO Customers
	VALUES (8, 'HELING', 'RUPERT');
INSERT INTO Customers
	VALUES (9, 'HAFFERKAMP', 'CUC');
INSERT INTO Customers
	VALUES (10, 'DUKELOW', 'CORETTA');
INSERT INTO Customers
	VALUES (11, 'STADICK', 'MIGDALIA');
INSERT INTO Customers
	VALUES (12, 'MCMAHAN', 'MELLIE');
INSERT INTO Customers
	VALUES (13, 'ARNN', 'KIP');
INSERT INTO Customers
	VALUES (14, 'SOPKO', 'RAYFORD');
INSERT INTO Customers
	VALUES (15, 'CALLENDAR', 'DAVID');
INSERT INTO Customers
	VALUES (16, 'CRUZEN', 'ARIANE');
INSERT INTO Customers
	VALUES (17, 'MESDAQ', 'CHARLENE');
INSERT INTO Customers
	VALUES (18, 'DOMKOWSKI', 'ALMETA');
INSERT INTO Customers
	VALUES (19, 'STENZ', 'NATACHA');
INSERT INTO Customers
	VALUES (20, 'ZEME', 'STEPHEN');
