-- Name: Ishaan Sathaye
-- Cal Poly Email: isathaye@calpoly.edu

INSERT INTO Teachers
	VALUES ('MACROSTIE', 'MIN', 101);
INSERT INTO Teachers
	VALUES ('COVIN', 'JEROME', 102);
INSERT INTO Teachers
	VALUES ('MOYER', 'OTHA', 103);
INSERT INTO Teachers
	VALUES ('NIBLER', 'JERLENE', 104);
INSERT INTO Teachers
	VALUES ('MARROTTE', 'KIRK', 105);
INSERT INTO Teachers
	VALUES ('TARRING', 'LEIA', 106);
INSERT INTO Teachers
	VALUES ('URSERY', 'CHARMAINE', 107);
INSERT INTO Teachers
	VALUES ('ONDERSMA', 'LORIA', 108);
INSERT INTO Teachers
	VALUES ('KAWA', 'GORDON', 109);
INSERT INTO Teachers
	VALUES ('SUMPTION', 'GEORGETTA', 110);
INSERT INTO Teachers
	VALUES ('KRIENER', 'BILLIE', 111);
INSERT INTO Teachers
	VALUES ('SUGAI', 'ALFREDA', 112);
