-- Name: Ishaan Sathaye
-- Cal Poly Email: isathaye@calpoly.edu

INSERT INTO List
	VALUES ('CAR', 'MAUDE', 2, 101);
INSERT INTO List
	VALUES ('KRISTENSEN', 'STORMY', 6, 112);
INSERT INTO List
	VALUES ('VANDERWOUDE', 'SHERWOOD', 3, 107);
INSERT INTO List
	VALUES ('NOGODA', 'ISMAEL', 0, 105);
INSERT INTO List
	VALUES ('DANESE', 'JANEE', 4, 111);
INSERT INTO List
	VALUES ('AMY', 'PATRINA', 1, 102);
INSERT INTO List
	VALUES ('PREHM', 'SHANEL', 0, 104);
INSERT INTO List
	VALUES ('GRUNIN', 'EMILE', 5, 109);
INSERT INTO List
	VALUES ('GELL', 'TAMI', 0, 104);
INSERT INTO List
	VALUES ('MADLOCK', 'RAY', 4, 110);
INSERT INTO List
	VALUES ('SUDA', 'DARLEEN', 4, 110);
INSERT INTO List
	VALUES ('DROP', 'SHERMAN', 0, 104);
INSERT INTO List
	VALUES ('PINNELL', 'ROBBY', 3, 107);
INSERT INTO List
	VALUES ('BROMLEY', 'EVELINA', 1, 103);
INSERT INTO List
	VALUES ('YUEN', 'ANIKA', 1, 103);
INSERT INTO List
	VALUES ('BUSTILLOS', 'HILMA', 0, 106);
INSERT INTO List
	VALUES ('GOODNOE', 'GAYLE', 4, 111);
INSERT INTO List
	VALUES ('BALBOA', 'MEL', 1, 103);
INSERT INTO List
	VALUES ('BARTKUS', 'REYNALDO', 1, 102);
INSERT INTO List
	VALUES ('GROENEWEG', 'CRYSTA', 3, 107);
INSERT INTO List
	VALUES ('HOUTCHENS', 'THEO', 0, 106);
INSERT INTO List
	VALUES ('GERSTEIN', 'AL', 5, 109);
INSERT INTO List
	VALUES ('MACIAG', 'CHET', 5, 109);
INSERT INTO List
	VALUES ('SAADE', 'TOBIE', 4, 110);
INSERT INTO List
	VALUES ('BRINE', 'FRANKLYN', 0, 106);
INSERT INTO List
	VALUES ('HANNEMANN', 'CHANTAL', 1, 102);
INSERT INTO List
	VALUES ('BYRUM', 'BENNIE', 0, 105);
INSERT INTO List
	VALUES ('NETZEL', 'JODY', 0, 105);
INSERT INTO List
	VALUES ('VANVLIET', 'COLLIN', 0, 106);
INSERT INTO List
	VALUES ('HONES', 'GUILLERMINA', 0, 104);
INSERT INTO List
	VALUES ('FLACHS', 'JEFFRY', 5, 109);
INSERT INTO List
	VALUES ('GRABILL', 'JULIENNE', 0, 106);
INSERT INTO List
	VALUES ('AREHART', 'VERTIE', 3, 107);
INSERT INTO List
	VALUES ('RUNKLE', 'MARCUS', 1, 102);
INSERT INTO List
	VALUES ('MOWATT', 'KITTIE', 0, 105);
INSERT INTO List
	VALUES ('HOOSOCK', 'LANCE', 1, 103);
INSERT INTO List
	VALUES ('LEAPER', 'ADRIAN', 4, 111);
INSERT INTO List
	VALUES ('PASSEY', 'RAYLENE', 4, 110);
INSERT INTO List
	VALUES ('NAKAHARA', 'SHERON', 0, 105);
INSERT INTO List
	VALUES ('STIRE', 'SHIRLEY', 6, 112);
INSERT INTO List
	VALUES ('RODDEY', 'CYRUS', 4, 110);
INSERT INTO List
	VALUES ('CRANMER', 'CAREY', 5, 109);
INSERT INTO List
	VALUES ('SCHUTZE', 'LANELLE', 5, 109);
INSERT INTO List
	VALUES ('FULVIO', 'ELTON', 4, 111);
INSERT INTO List
	VALUES ('HOESCHEN', 'LYNNETTE', 4, 108);
INSERT INTO List
	VALUES ('SOLOMAN', 'BRODERICK', 0, 106);
INSERT INTO List
	VALUES ('LAPLANT', 'SUMMER', 2, 101);
INSERT INTO List
	VALUES ('LUSKEY', 'BRITT', 4, 108);
INSERT INTO List
	VALUES ('JAGNEAUX', 'ELVIRA', 6, 112);
INSERT INTO List
	VALUES ('BIBB', 'SHANAE', 1, 103);
INSERT INTO List
	VALUES ('WIRTZFELD', 'DELORAS', 0, 106);
INSERT INTO List
	VALUES ('RANSLER', 'RODGER', 1, 102);
INSERT INTO List
	VALUES ('NABOZNY', 'CHRISSY', 3, 107);
INSERT INTO List
	VALUES ('ATWOOD', 'BETHEL', 5, 109);
INSERT INTO List
	VALUES ('CHIARAMONTE', 'NOVELLA', 2, 101);
INSERT INTO List
	VALUES ('TRAYWICK', 'KERI', 1, 102);
INSERT INTO List
	VALUES ('BRIGHTBILL', 'ANTONY', 1, 102);
INSERT INTO List
	VALUES ('HUANG', 'TAWANNA', 5, 109);
INSERT INTO List
	VALUES ('SANTORY', 'JORDON', 3, 107);
INSERT INTO List
	VALUES ('LARKINS', 'GAYLE', 4, 110);
